# render.yaml
# CORRECTED: This version uses the proper schema for Render's Blueprint spec.

services:
  # ----------------------------------------------------------------------
  # A PostgreSQL database for Metabase's own application data.
  # ----------------------------------------------------------------------
  - type: pserv
    name: metabase-app-db
    databaseName: metabase_app_data
    user: metabase_user
    plan: free # Use 'starter' for production. Free plans may sleep.

  # ----------------------------------------------------------------------
  # The Metabase Web Service itself, running from the official Docker image.
  # ----------------------------------------------------------------------
  - type: web
    name: metabase
    env: docker # Specifies we are running a Docker container
    plan: ree # Recommended to prevent sleeping. Options: free, starter, etc.

    # --- CORRECTED SECTION ---
    # Docker-specific properties must be nested under a 'docker' block.
    # The key is 'image', not 'dockerImage'.
    docker:
      image: metabase/metabase:latest

    # The health check is a top-level property for a web service and is correct.
    healthCheck:
      path: /api/health
      initialDelaySeconds: 90 # Give Metabase time to start up

    # Environment variables to configure Metabase to use our Postgres DB.
    envVars:
      - key: MB_DB_TYPE
        value: postgres
      - key: MB_DB_CONNECTION_URI
        fromDatabase:
          name: metabase-app-db # Must match the name of the database service
          property: connectionString
      - key: JAVA_TIMEZONE
        value: UTC # Set to your preferred timezone, e.g., America/New_York
